version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  cambio-db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin123"
    expose:
      - "54321"
    ports:
      - "54321:54321"
    volumes:
      - ./cambio-docker-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 54321
    networks:
      - microservices-net

  book-db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin123"
    expose:
      - "54322"
    ports:
      - "54322:54322"
    volumes:
      - ./book-docker-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 54322
    networks:
      - microservices-net

  naming-server:
    image: brunocesar96/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks: #Rede de comunicação entre os microserviços
      - microservices-net

  api-gateway:
    image: brunocesar96/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge