version: '3.4'

services:
  naming-server:
    image: brunocesar96/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks: #Rede de comunicação entre os microserviços
      - microservices-net
networks:
  microservices-net:
    driver: bridge