version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  naming-server:
    image: brunocesar96/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks: #Rede de comunicação entre os microserviços
      - microservices-net

  api-gateway:
    image: brunocesar96/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge