global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8100']
        labels:
          application: 'api-books'
      - targets: ['172.17.0.1:8000']
        labels:
          application: 'api-cambios'
